name: STEPHANO BUTTO
favicon: null
layout_spectrum: 0.89499
typography_spectrum: 0.9131
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#fffbf8'
    - '#5a4e4e'
    - '#99b4d2'
    - '#ddd3ca'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0
  rhythmicContrast: 0
purpose: []
